//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doanquanlythuvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string MaNXB { get; set; }
        public string MaTacGia { get; set; }
        public string MaTheLoai { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TenNXB { get; set; }
        public string TenTacGia { get; set; }
        public string TenTheLoai { get; set; }
    
        public virtual NXB NXB { get; set; }
        public virtual TACGIA TACGIA { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
